Repository mfld-fr/emu86, pull requests merged in 2020-10, with the labels that each got.

#6 Fixes to run with latest ELKS kernel
  Makefile
  emu-console.c
  emu-main.c
  emu-serial.h
  op-exec.c
Labels: fix, improvement

#7 Add AT&T-style instruction mnemonic display
  Makefile
  op-class.c
  op-common.c
  op-id-name.c
  op-id-name.h
  op-print-att.c
  op-print-intel.c
Labels: improvement

#10 More explicit operand size
  op-class.c
  op-class.h
  op-id-name.c
  op-id-name.h
  op-print-att.c
  op-print-intel.c
Labels: improvement

#13 Fix console raw mode with usage() and abort() calls
  emu-console.c
Labels: fix

#17 Fix console when serial_recv called with no input ready
  emu-console.c
Labels: fix

#14 Optionalize target support
  .gitignore
  Makefile
  README
  emu-int.c
  emu-int.h
  emu-main.c
  emu-mem-io.c
  emu-mem-io.h
  emu-serial.c
  emu-serial.h
  emu-timer.h
  int-advtech.c
  int-advtech.h
  int-elks.c
  int-elks.h
  io-advtech.c
  io-elks.c
  op-class.c
  op-exec.c
  op-exec.h
  serial-advtech.c
  serial-advtech.h
  serial-console.c
  serial-elks.c
  serial-pty.c
  timer-advtech.c
  timer-advtech.h
  timer-elks.c
Labels: enhancement, improvement
