Repository mfld-fr/emu86, pull requests merged in 2021-05, with the labels that each got.

#33 New layout for devices & backends
  Makefile
  README.md
  char-pty.c
  char-stdio.c
  con-char.c
  con-sdl.c
  con-sdl.h
  elks.sh
  emu-char.h
  emu-con.h
  emu-int.h
  emu-main.c
  emu-mem-io.h
  emu-proc.c
  emu-proc.h
  emu-serial.h
  emu-timer.h
  emu-types.h
  int-advtech.h
  op-class.h
  op-common.h
  op-id-name.h
  op-id.h
  op-print-att.c
  rom-elks.c
  serial-advtech.c
  serial-advtech.h
  serial-elks.c
  timer-advtech.h
Labels: improvement

#35 Activate automatic build of default configuration
  .github/workflows/default.yml
Labels: enhancement

#34 Tune serial subsystem & ease configuration
  Makefile
  README.md
  con-char.c
  con-none.c
  config-advtech.mk
  config-elks.mk
  config.mk
  emu-char.h
  emu-serial.c
  emu-serial.h
  op-print-intel.c
  rom-advtech.c
  serial-advtech.c
  serial-char.c
  serial-elks.c
  serial-none.c
Labels: improvement

#36 SDL console integration
  Makefile
  README
  README.md
  char-pty.c
  char-stdio.c
  con-char.c
  con-none.c
  con-sdl.c
  con-sdl.h
  config-advtech.mk
  config-elks.mk
  config.mk
  elks.sh
  emu-char.h
  emu-con.h
  emu-int.h
  emu-main.c
  emu-mem-io.h
  emu-proc.c
  emu-proc.h
  emu-serial.c
  emu-serial.h
  emu-timer.h
  emu-types.h
  int-advtech.c
  int-advtech.h
  int-elks.c
  int-elks.h
  op-class.h
  op-common.h
  op-id-name.h
  op-id.h
  op-print-att.c
  op-print-intel.c
  rom-advtech.c
  rom-elks.c
  rom8x16.c
  serial-advtech.c
  serial-advtech.h
  serial-char.c
  serial-elks.c
  serial-none.c
  timer-advtech.h
Labels: enhancement

#38 Fix Control-C Linux terminal exit
  char-stdio.c
  rom-elks.c
Labels: fix

#37 Refactor main loop
  char-stdio.c
  emu-main.c
Labels: improvement

#40 Tune SDL and Emscripten/browser platforms
  README.md
  elks.sh
  emu-main.c
  timer-elks.c
Labels: improvement

#42 Add support for ELKS BIOS console
  con-char.c
  con-none.c
  con-sdl.c
  emu-con.h
  emu-main.c
  io-elks.c
  rom-elks.c
  timer-elks.c
Labels: fix, improvement

#43 Cleanup ELKS specific code
  emu-int.h
  emu-main.c
  rom-advtech.c
  rom-elks.c
Labels: improvement

#45 main: allow multiple breakpoints to be specified
  emu-main.c
Labels: improvement

#46 Add keyboard queue to SDL console
  Makefile
  char-pty.c
  char-stdio.c
  con-sdl.c
  con-sdl.h
  emu-types.h
  rom-elks.c
Labels: improvement

#48 Extend queuing to character console
  Makefile
  con-char.c
  con-none.c
  con-sdl.c
  emu-con.c
  emu-con.h
  emu-main.c
Labels: improvement

#49 Fix disk id BIOS bug
  rom-elks.c
Labels: fix

#53 Fix INT 13h disk error vs unimplemented function
  rom-elks.c
Labels: fix

#54 Implement transparent cursor and reverse video in SDL backend
  con-sdl.c
  rom-elks.c
Labels: improvement

#55 Remove assert calls from ELKS BIOS
  rom-elks.c
Labels: improvement

#58 Fix ELKS ROM BIOS to handle video text attributes
  con-char.c
  con-none.c
  con-sdl.c
  emu-con.h
  mem-io-elks.h
  rom-elks.c
Labels: fix

#63 Fix the ELKS auto-build
  .github/workflows/default.yml
Labels: fix

#66 Apply buggy keyboard peek fix to ELKS BIOS
  rom-elks.c
Labels: fix

#67 Refine MDA attributes and IPS option
  con-sdl.c
  emu-main.c
  emu-mem-io.c
  mem-io-elks.h
  rom-bios.h
  rom-elks.c
  rom-pcxtat.c
Labels: improvement

#69 Add BDA equipment word specifying # disk drives
  rom-elks.c
  rom-pcxtat.c
Labels: fix

#68 Merge 'next' branch into 'master'
  README.md
  con-char.c
  con-none.c
  con-sdl.c
  config-advtech.mk
  config-elks.mk
  config.mk
  emu-con.h
  emu-int.c
  emu-main.c
  emu-mem-io.c
  mem-advtech.c
  mem-elks.c
  mem-io-elks.h
  op-class.c
  op-exec.c
  op-id-name.c
  rom-advtech.c
  rom-bios.c
  rom-bios.h
  rom-elks.c
  rom-pcxtat.c
  timer-elks.c
Labels: fix, improvement

#72 Add CPU - PLATFORM - BOARD triplet
  Makefile
  con-sdl.c
  int-8xxx.c
  int-8xxx.h
  int-r8810.c
  int-r8810.h
  io-advtech.c
  io-pcxtat.c
  mem-io-pcxtat.h
  mem-pcxtat.c
  msdos.sh
  rom-advtech.c
  rom-elks.c
  rom-pcxtat.c
  serial-8xxx.c
  serial-r8810.c
  serial-r8810.h
  timer-8xxx.c
  timer-8xxx.h
  timer-r8810.c
  timer-r8810.h
Labels: improvement

#71 Add text segment symbol display to disassembler
  Makefile
  config.mk
  convmap.c
  convmap.sh
  mapfile.c
  op-print-att.c
Labels: enhancement

#73 Add Orkitt 556 board preliminary support
  Makefile
  config-or556.mk
  config.mk
  emu-mem-io.c
  emu-mem-io.h
  int-8018x.c
  int-8018x.h
  io-or556.c
  mem-or556.c
  rom-or556.c
  serial-8018x.c
  serial-8018x.h
  timer-8018x.c
  timer-8018x.h
Labels: enhancement

#76 timer-801x.inc: Timer2 control reg index fix
  timer-8018x.inc
Labels: fix

#75 int-8018x: add nonspecific EOI
  int-8018x.c
Labels: improvement

#74 serial-8018x: add receive status and buffer
  serial-8018x.c
Labels: improvement
