Repository mfld-fr/emu86, pull requests merged in 2021-04, with the labels that each got.

#28 Add some 80186 instructions
  op-class.c
  op-exec.c
  op-id-name.c
  op-id.h
Labels: improvement

#29 Add memory operand option for XLAT
  op-exec.c
Labels: fix

#24 Timer interrupt revision
  emu-int.c
  emu-int.h
  emu-main.c
  int-advtech.c
  int-advtech.h
  int-elks.c
  int-elks.h
  io-elks.c
  op-class.c
  op-print-att.c
  timer-elks.c
Labels: improvement

#27 Add console driver for SDL / Emscripten (browser) support
  Makefile
  emu-main.c
  rom8x16.c
  serial-sdl.c
  serial-sdl.h
Labels: enhancement
